gamma: 0.999
gae_lambda: 0.95
num_steps: 128
num_epochs: 3
num_minibatches: 8
ent_coef: 0.01
clip_range: 0.2
learning_rate: 5.0e-4
norm_adv: true
clip_vloss: true
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: null
anneal_lr: true