#! /usr/bin/env bash
filename=$(basename $1 .pdf)
gs -dPDFA -dBATCH -dNOPAUSE \
  -sColorConversionStrategy=UseDeviceIndependentColor \
  -sDEVICE=pdfwrite -dPDFACompatibilityPolicy=2       \
  -sOutputFile=$filename-pdfa.pdf \
  $1
